server:
  port: 8083
spring:
  application:
    name: GuideDx IAM Service
  datasource:
    url: jdbc:postgresql://localhost:5432/Diagnostic Decision Engine
    username: postgres
    password: dhe@1234
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql : true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#eureka:
#  client:
#    enabled: false
    